version: '3.0'

services: 
    redis:
        restart: always
        build: 
            context: .
            dockerfile: redis/Dockerfile
        ports: 
            - "6379:6379"
        networks: 
            - alm-network

networks: 
    alm-network:
        driver: bridge