version: '3.0'

services: 
    redis:
        restart: always
        build: 
            context: .
            dockerfile: redis/Dockerfile
        ports: 
            - "6379:6379"
        networks: 
            - asg-network

networks: 
    asg-network:
        driver: bridge